version: '3.8'

services:
  app:
    image: openjdk:17-jdk-slim  # Use Java 17 base image
    container_name: t1debut-app2
    build:
      context: .                 # Build context, assuming Dockerfile is in the project root
      dockerfile: Dockerfile
    ports:
      - "8080:8080"              # Expose the Spring Boot app on port 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/t1_test  # Use service name instead of localhost
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: deadbeef
      SPRING_JPA_HIBERNATE_DDL_AUTO: update  # Ensure schema is updated on start
    depends_on:
      - db

  db:
    image: postgres:17   # PostgreSQL image version
    container_name: t1debut-app
    environment:
      POSTGRES_DB: t1_test            # Database name
      POSTGRES_USER: postgres          # Database user
      POSTGRES_PASSWORD: deadbeef      # Database password
    ports:
      - "5432:5432"              # Expose PostgreSQL on port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data in a named volume

volumes:
  postgres_data:
